# Generated by Django 5.1.4 on 2024-12-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='image_url',
            field=models.URLField(default='https://i.imghippo.com/files/bQyI7776Dg.webp'),
        ),
    ]
