# Generated by Django 5.1.4 on 2025-01-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_comment_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auctionlisting",
            name="image_url",
        ),
        migrations.AddField(
            model_name="auctionlisting",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="auction_images/"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="comment/"),
        ),
    ]
