# Generated by Django 5.1.4 on 2025-01-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_bid_amount_alter_bid_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bid',
            name='unique_bid_per_time',
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bid',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
