# Generated by Django 6.1.1 on 2026-09-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_remove_bid_unique_bid_per_time_alter_bid_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
