# Generated by Django 6.0.7 on 2026-08-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinestage",
            name="is_final",
            field=models.BooleanField(default=False),
        ),
    ]
