# Generated by Django 6.1.1 on 2026-09-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_pipelinestage_is_final"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deal",
            name="tags",
        ),
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("call", "Call"),
                    ("email", "E-mail"),
                    ("meeting", "Meet"),
                    ("note", "Note"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
