-- ============================================================
-- EXAMPLE DATA
-- PostgreSQL
-- Consistent with the schema generated by Django migrations
-- (app "network")
-- ============================================================


-- ============================================================
-- USERS
-- ============================================================
--
-- User 1 = user           (username: user)
-- User 2 = Pepe           (username: pepe)
-- User 3 = Dogecoin       (username: dogecoin)
--
-- Passwords:
-- user@example.com     / password
-- pepe@example.com     / password
-- dogecoin@example.com / password
--
-- IMPORTANT:
-- The password hash below is kept exactly as provided.
-- ============================================================

INSERT INTO network_user (
    id,
    password,
    last_login,
    is_superuser,
    username,
    first_name,
    last_name,
    email,
    is_staff,
    is_active,
    date_joined,
    profile_picture
)
VALUES
(
    1,
    'pbkdf2_sha256$600000$example$NM3mC9boABgLTl2uIwgt0x5awBSmVkt0hdsdqcbt1cY=',
    NULL,
    TRUE,
    'user',
    'Example',
    'User',
    'user@example.com',
    FALSE,
    TRUE,
    '2026-08-18 18:05:00',
    NULL
),
(
    2,
    'pbkdf2_sha256$600000$example$NM3mC9boABgLTl2uIwgt0x5awBSmVkt0hdsdqcbt1cY=',
    NULL,
    FALSE,
    'pepe',
    'Pepe',
    'User',
    'pepe@example.com',
    FALSE,
    TRUE,
    '2026-08-18 18:06:00',
    'https://fl0bg7voit1klxrh.public.blob.vercel-storage.com/network/profiles/ZgnaoxbVZu.webp'
),
(
    3,
    'pbkdf2_sha256$600000$example$NM3mC9boABgLTl2uIwgt0x5awBSmVkt0hdsdqcbt1cY=',
    NULL,
    FALSE,
    'dogecoin',
    'Dogecoin',
    'User',
    'dogecoin@example.com',
    FALSE,
    TRUE,
    '2026-08-18 18:06:00',
    'https://fl0bg7voit1klxrh.public.blob.vercel-storage.com/network/profiles/XggFs3wdqc.webp'
)
ON CONFLICT DO NOTHING;


-- ============================================================
-- FOLLOWS
-- ============================================================
--
-- Follow A: record owned by "user", followed by "Pepe"
--           (Pepe follows user)
--
-- Follow B: record owned by "Pepe", followed by "user"
--           (user follows Pepe)
-- ============================================================

INSERT INTO network_follow (
    id,
    user_id
)
VALUES
(
    1,
    1
),
(
    2,
    2
)
ON CONFLICT DO NOTHING;


INSERT INTO network_follow_followed_by (
    id,
    follow_id,
    user_id
)
VALUES
(
    1,
    1,
    2
),
(
    2,
    2,
    1
)
ON CONFLICT DO NOTHING;


-- ============================================================
-- TWEETS
-- ============================================================
--
-- Tweet 1: posted by Pepe, on vacation boating on the ocean
-- Tweet 2: posted by user, random topic, no image
-- Tweet 3: posted by Pepe, at the zoo watching the elephant enclosure
-- Tweet 4: posted by user, claiming to be a fan of Pepe, met him near
--          the Palace of Culture and Science in Warsaw and took a photo
-- Tweet 5: posted by Pepe, currently at a birthday party
-- Tweet 6: posted by Dogecoin, looking at memes about himself
-- Tweet 7: posted by Dogecoin, reacting to a meme about himself
-- Tweet 8: posted by Dogecoin, reacting to another meme about himself
-- ============================================================

INSERT INTO network_tweet (
    id,
    "tweetText",
    "tweetImage",
    posted,
    author_id
)
VALUES
(
    1,
    'On vacation right now, just took the boat out onto the ocean. Absolutely perfect day out here!',
    'https://fl0bg7voit1klxrh.public.blob.vercel-storage.com/network/tweets/IlGqDZY84G.webp',
    '2026-08-18 18:15:00',
    2
),
(
    2,
    'Finally organized my desk after weeks of putting it off. Small wins, but it feels great.',
    NULL,
    '2026-08-18 18:20:00',
    1
),
(
    3,
    'At the zoo today, standing by the elephant enclosure. These animals are even bigger up close than I imagined!',
    'https://fl0bg7voit1klxrh.public.blob.vercel-storage.com/network/tweets/XpAL3VzL5g.webp',
    '2026-08-18 18:30:00',
    2
),
(
    4,
    'Could not believe it when I ran into Pepe near the Palace of Culture and Science in Warsaw today. Managed to grab a photo with him, what a moment!',
    'https://fl0bg7voit1klxrh.public.blob.vercel-storage.com/network/tweets/Si8cbQUF4U.webp',
    '2026-08-18 18:40:00',
    1
),
(
    5,
    'At a birthday party right now, having an absolutely amazing time. Best night in a while!',
    'https://fl0bg7voit1klxrh.public.blob.vercel-storage.com/network/tweets/FkAAufVXBF.webp',
    '2026-08-18 18:50:00',
    2
),
(
    6,
    'I cannot stop scrolling through all the memes people are making about me on the internet. Some of these are absolutely hilarious!',
    NULL,
    '2026-08-18 19:00:00',
    3
),
(
    7,
    'Just found this meme about me and honestly, I have no idea whether I should laugh or be offended. Internet people are something else!',
    'https://fl0bg7voit1klxrh.public.blob.vercel-storage.com/network/tweets/AHTIhKehYu.webp',
    '2026-08-18 19:10:00',
    3
),
(
    8,
    'And then I found another meme about myself. At this point I am starting to wonder if there is a whole internet dedicated to turning everything I do into a meme.',
    'https://fl0bg7voit1klxrh.public.blob.vercel-storage.com/network/tweets/hMtjqf65wf.webp',
    '2026-08-18 19:20:00',
    3
)
ON CONFLICT DO NOTHING;


-- ============================================================
-- TWEET LIKES
-- ============================================================

INSERT INTO network_tweet_like (
    id,
    tweet_id,
    user_id
)
VALUES
(
    1,
    1,
    1
),
(
    2,
    3,
    1
),
(
    3,
    4,
    2
),
(
    4,
    5,
    1
)
ON CONFLICT DO NOTHING;


-- ============================================================
-- RESET SEQUENCES
-- ============================================================
--
-- Important when manually inserting IDs into PostgreSQL.
-- This prevents the next Django-created object from trying
-- to reuse an already existing ID.
-- ============================================================

SELECT setval(
    pg_get_serial_sequence('network_user', 'id'),
    COALESCE((SELECT MAX(id) FROM network_user), 1),
    true
);

SELECT setval(
    pg_get_serial_sequence('network_follow', 'id'),
    COALESCE((SELECT MAX(id) FROM network_follow), 1),
    true
);

SELECT setval(
    pg_get_serial_sequence('network_follow_followed_by', 'id'),
    COALESCE((SELECT MAX(id) FROM network_follow_followed_by), 1),
    true
);

SELECT setval(
    pg_get_serial_sequence('network_tweet', 'id'),
    COALESCE((SELECT MAX(id) FROM network_tweet), 1),
    true
);

SELECT setval(
    pg_get_serial_sequence('network_tweet_like', 'id'),
    COALESCE((SELECT MAX(id) FROM network_tweet_like), 1),
    true
);