# Generated by Django 5.1.4 on 2025-01-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0010_alter_follow_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
