# Generated by Django 5.1.4 on 2025-01-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweetImage',
            field=models.ImageField(blank=True, null=True, upload_to='tweet_media/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_media/'),
        ),
    ]
