# Generated by Django 6.1.1 on 2026-09-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0013_alter_follow_id_alter_tweet_id_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="tweetImage",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
