# Generated by Django 6.1.1 on 2026-09-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0014_alter_tweet_tweetimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
